name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for your fist issue. We are glad you are helping us to improve our tools.'
        pr-message: 'Thank you for your first contibution to our code. We value it and we are glad you are helping us.'
